#[path = "event_persistence.rs"]
pub mod event_repository;
#[path = "payment_persistence.rs"]
pub mod payment_repository;
#[path = "user_persistence.rs"]
pub mod user_repository;
#[path = "genre_persistence.rs"]
pub mod genre_repository;
#[path = "club_persistence.rs"]
pub mod club_repository;
#[path = "ticket_persistence.rs"]
pub mod ticket_repository;
#[path = "table_persistence.rs"]
pub mod table_repository;
#[path = "club_owner_persistence.rs"]
pub mod club_owner_repository;
#[path = "area_persistence.rs"]
pub mod area_repository;
